#!/bin/bash

# Setup Hostname 
sudo hostnamectl set-hostname "dev.cloudbinary.io"

# Update the hostname part of Host File
echo "`hostname -I | awk '{ print $1 }'` `hostname`" >> /etc/hosts 
#cat /etc/hosts


# Update Ubuntu Repository 
apt update 

# Download, & Install Utility Softwares 
apt install git wget unzip curl tree -y 

# Download, Install Java 11
sudo apt-get install openjdk-11-jdk -y

# Backup the Environment File
sudo cp -pvr /etc/environment "/etc/environment_$(date +%F_%R)"

# Create Environment Variables 
echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/" >> /etc/environment

# Compile the Configuration 
source /etc/environment

# Go to /opt directory to download Apache Tomcat 
cd /opt/

# Download Apache Tomcat - Application
sudo wget https://downloads.apache.org/tomcat/tomcat-8/v8.5.84/bin/apache-tomcat-8.5.84.tar.gz

# Extract the Tomcat File
sudo tar xvzf apache-tomcat-8.5.84.tar.gz

# Rename the Tomcat Folder
sudo mv apache-tomcat-8.5.84 tomcat

# Go Inside the Tomcat Folder
cd /opt/tomcat/

# Take Tomcat Configuration as backup 
sudo cp -pvr /opt/tomcat/conf/tomcat-users.xml "/opt/tomcat/conf/tomcat-users.xml_$(date +%F_%R)"

# To delete last line and which contains </tomcat-users>
sed -i '$d' /opt/tomcat/conf/tomcat-users.xml

#Add User & Attach Roles to Tomcat 
'<role rolename="manager-gui"/>'
'<role rolename="manager-script"/>'
'<role rolename="manager-jmx"/>'   
'<role rolename="manager-status"/>' 
'<role rolename="admin-gui"/>'    
'<role rolename="admin-script"/>''
<user username="admin" password="redhat@123" roles="manager-gui,manager-script,manager-jmx,manager-status,admin-gui,admin-script"/>' >> /opt/tomcat/conf/tomcat-users.xml
"</tomcat-users>" >> /opt/tomcat/conf/tomcat-users.xml

# Start Tomcat Server





# To Restart SSM Agent on Ubuntu 
#sudo systemctl restart snap.amazon-ssm-agent.amazon-ssm-agent.service

# Attach Instance profile To EC2 Instance 
# aws ec2 associate-iam-instance-profile --iam-instance-profile Name=SA-EC2-SSM --instance-id ""


# Verify:
# http://192.168.29.56:8080

# vi /opt/tomcat/webapps/host-manager/META-INF/context.xml

# grep -H -n "|.*" webapps/host-manager/META-INF/context.xml
# webapps/host-manager/META-INF/context.xml:20:         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|.*" />

# vi /opt/tomcat/webapps/manager/META-INF/context.xml

# grep -H -n "|.*" webapps/manager/META-INF/context.xml
# webapps/manager/META-INF/context.xml:20:         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1|.*" />



<role rolename="manager-gui"/>
<role rolename="manager-script"/>
<role rolename="manager-jmx"/> 
<role rolename="manager-status"/> 
<role rolename="admin-gui"/> 
<role rolename="admin-script"/>
<user username="admin" password="redhat@123" roles="manager-gui,manager-script,manager-jmx,manager-status,admin-gui,admin-script"/>
"</tomcat-users>"S